# Minimal stub for Klipper's klippy/klippy.py -- only the members actually
# used by this project's extras/*.py.
from typing import Any, Callable, Dict, Optional

from configfile import ConfigWrapper
from reactor import SelectReactor

message_ready: str

class Printer:
    config_error: type[Exception]
    command_error: type[Exception]
    start_args: Dict[str, Any]
    reactor: SelectReactor
    state_message: str
    in_shutdown_state: bool
    run_result: Optional[str]
    event_handlers: Dict[str, list]
    objects: Dict[str, Any]

    def get_start_args(self) -> Dict[str, Any]: ...
    def get_reactor(self) -> SelectReactor: ...
    def get_state_message(self) -> tuple: ...
    def is_shutdown(self) -> bool: ...
    def add_object(self, name: str, obj: Any) -> None: ...
    def lookup_object(self, name: str, default: Any = ...) -> Any: ...
    def lookup_objects(self, module: Optional[str] = None) -> list: ...
    def load_object(self, config: ConfigWrapper, section: str, default: Any = ...) -> Any: ...
    def register_event_handler(self, event: str, callback: Callable) -> None: ...
    def send_event(self, event: str, *params: Any) -> list: ...
    def invoke_shutdown(self, msg: str, details: dict = ...) -> None: ...
    def invoke_async_shutdown(self, msg: str) -> None: ...
    def request_exit(self, result: str) -> None: ...
    # Snapmaker U1 fork additions -- not part of mainline Klipper.
    def update_snapmaker_config_file(self, *args: Any, **kwargs: Any) -> None: ...
