# Minimal stub for Klipper's klippy/mcu.py -- only the members actually
# used by this project's extras/*.py. setup_minmax/the report_time arg on
# setup_adc_callback are Kalico-only additions (this project supports both
# Klipper and Kalico), included alongside mainline's setup_adc_sample.
from typing import Any, Callable, Optional, Sequence, Tuple, overload

from klippy import Printer

class error(Exception): ...

class MCU:
    def estimated_print_time(self, eventtime: float) -> float: ...

def get_printer_mcu(printer: Printer, name: str) -> MCU: ...

class CommandWrapper:
    def send(self, data: Sequence = (), minclock: int = 0, reqclock: int = 0) -> None: ...
    def send_wait_ack(self, data: Sequence = (), minclock: int = 0, reqclock: int = 0) -> None: ...
    def get_command_tag(self) -> int: ...

class CommandQueryWrapper:
    def send(self, data: Sequence = (), minclock: int = 0, reqclock: int = 0,
              retry: bool = True) -> Any: ...
    def send_with_preface(self, preface_cmd: CommandWrapper, preface_data: Sequence = (),
                           data: Sequence = (), minclock: int = 0, reqclock: int = 0,
                           retry: bool = True) -> Any: ...

class MCU_endstop:
    def get_mcu(self) -> MCU: ...
    def add_stepper(self, stepper: Any) -> None: ...
    def get_steppers(self) -> list: ...
    def home_start(self, print_time: float, sample_time: float, sample_count: int,
                   rest_time: float, triggered: bool = True) -> Any: ...
    def home_wait(self, home_end_time: float) -> float: ...
    def query_endstop(self, print_time: float) -> int: ...

class MCU_adc:
    def get_mcu(self) -> MCU: ...
    def setup_minmax(self, sample_time: float, sample_count: int, minval: float = 0.,
                      maxval: float = 1., range_check_count: int = 0) -> None: ...
    def setup_adc_sample(self, report_time: float = ..., sample_time: float = 0.,
                          sample_count: int = 1, batch_num: int = 1, minval: float = 0.,
                          maxval: float = 1., range_check_count: int = 0) -> None: ...
    @overload
    def setup_adc_callback(self, callback: Callable) -> None: ...
    @overload
    def setup_adc_callback(self, report_time: float, callback: Callable) -> None: ...
    def get_last_value(self) -> Tuple[float, float]: ...
