# Minimal stub for Klipper's klippy/pins.py -- only the members actually
# used by this project's extras/*.py.
from typing import Any

class error(Exception): ...

class PrinterPins:
    error: type[error]

    def parse_pin(self, pin_desc: str, can_invert: bool = False,
                  can_pullup: bool = False) -> dict: ...
    def lookup_pin(self, pin_desc: str, can_invert: bool = False,
                   can_pullup: bool = False, share_type: Any = None) -> dict: ...
    def setup_pin(self, pin_type: str, pin_desc: str) -> Any: ...
    def allow_multi_use_pin(self, pin_desc: str) -> None: ...
