# Minimal stub for Klipper's klippy/reactor.py -- only the members
# actually used by this project's extras/*.py.
from typing import Any, Callable, Optional

class ReactorCompletion:
    def test(self) -> bool: ...
    def complete(self, result: Any) -> None: ...
    def wait(self, waketime: float = ..., waketime_result: Any = None) -> Any: ...

class SelectReactor:
    NOW: float
    NEVER: float

    def monotonic(self) -> float: ...
    def pause(self, waketime: float) -> float: ...
    def register_timer(self, callback: Callable, waketime: float = ...) -> Any: ...
    def update_timer(self, timer_handler: Any, waketime: float) -> None: ...
    def unregister_timer(self, timer_handler: Any) -> None: ...
    def register_callback(self, callback: Callable, waketime: float = ...) -> ReactorCompletion: ...
    def register_async_callback(self, callback: Callable, waketime: float = ...) -> None: ...
    def completion(self) -> ReactorCompletion: ...
    def mutex(self, is_locked: bool = False) -> Any: ...

class PollReactor(SelectReactor): ...
class EPollReactor(SelectReactor): ...
