# Minimal stub for Klipper's klippy/stepper.py -- only the members
# actually used by this project's extras/*.py. generate_steps is a
# Kalico-only addition (this project supports both Klipper and Kalico).
from typing import Any, Optional, Tuple

from mcu import MCU

class error(Exception): ...

class MCU_stepper:
    def get_mcu(self) -> MCU: ...
    def get_name(self, short: bool = False) -> str: ...
    def get_step_dist(self) -> float: ...
    def get_rotation_distance(self) -> Tuple[float, int]: ...
    def set_rotation_distance(self, rotation_dist: float) -> None: ...
    def set_position(self, coord: Tuple[float, float, float]) -> None: ...
    def get_commanded_position(self) -> float: ...
    def get_mcu_position(self, cmd_pos: Optional[float] = None) -> int: ...
    def get_stepper_kinematics(self) -> Any: ...
    def set_stepper_kinematics(self, sk: Any) -> Any: ...
    def get_trapq(self) -> Any: ...
    def set_trapq(self, tq: Any) -> Any: ...
    def generate_steps(self, flush_time: float) -> None: ...

# Real Klipper's stepper.PrinterStepper is a factory *function* that
# constructs an MCU_stepper; this project only ever uses it as a type
# annotation (`-> list[PrinterStepper]`), so it's stubbed as an alias here.
PrinterStepper = MCU_stepper
