# Minimal stub for Klipper's klippy/toolhead.py -- only the members
# actually used by this project's extras/*.py. note_mcu_movequeue_activity
# is a Kalico-only addition (this project supports both Klipper and Kalico).
from typing import Any, Callable, Dict, Optional, Tuple

from mcu import MCU

class ToolHead:
    # Internal attributes this project reaches into directly to implement
    # its own drip-move handling (mimicking Klipper's real drip_move).
    print_time: float
    special_queuing_state: str
    need_check_pause: float
    lookahead: Any
    check_stall_time: float
    can_pause: bool
    mcu: MCU

    def _advance_move_time(self, next_print_time: float) -> None: ...

    def get_position(self) -> list: ...
    def set_position(self, newpos: list, homing_axes: str = "") -> None: ...
    def move(self, newpos: list, speed: float) -> None: ...
    def dwell(self, delay: float) -> None: ...
    def wait_moves(self) -> None: ...
    def flush_step_generation(self) -> None: ...
    def get_last_move_time(self) -> float: ...
    def set_extruder(self, extruder: Any, extrude_pos: float) -> None: ...
    def get_extruder(self) -> Any: ...
    def get_status(self, eventtime: float) -> Dict[str, Any]: ...
    def get_kinematics(self) -> Any: ...
    def get_trapq(self) -> Any: ...
    def register_lookahead_callback(self, callback: Callable) -> None: ...
    def get_max_velocity(self) -> Tuple[float, float]: ...
    def note_mcu_movequeue_activity(self, mq_time: float,
                                     set_step_gen_time: bool = False) -> None: ...
